### ISSUE TITLE
--type sets scm instead of type

### ISSUE THREAD

**Issue by sbulka** [azimux/externals#11]
When I call 
```
bin/ext --type rails
```
then `scm` is set to `rails` in the `.externals` file.
That's no valid command for checkout.

**Comment by azimux** [comment]
Thanks!  I just merged a test for this and verified that this fixes it.  I haven't touched this thing in 6 years so it's crazy to go look at this code, which is over 10 years old and is some of the first Ruby I ever wrote.  So weird to grok.

**Comment by sbulka** [comment]
I am looking into using this gem so I can use svn+git "externals" uniformely.
It may happen I send some more PR if something breaks unexpectedly in the following days.

The features look very useful, and it's easy enough to "dig in" the code. :)
